[project]
org-name = "ballerinax"
version = "0.1.1"
authors = ["Ballerina"]
keywords = ["azure", "cv", "computervision", "vision", "ocr"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.cv"
license = ["Apache-2.0"]
